name: Generate Stats
on:
  schedule: [{cron: "0 0 * * *"}] # Roda Ã  meia-noite
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: generate-stats
        uses: soulteary/github-readme-stats@v1.0.0
        with:
          card: stats
          options: username=guigasprog&theme=radical&show_icons=true
          path: profile/stats.svg
          token: ${{ secrets.METRICS_TOKEN }}
